### PR TITLE
Cleanup dependencies

### PR DESCRIPTION
**Pull request by jackboberg**
Add `devDependencies` with correct packages.

### CODE REVIEW

**Comment by maxogden** [comment]
thanks. are you interested in helping maintain this by the way? always looking for more collaborators, http://openopensource.org/ style

**Comment by max-mapper** [comment]
thanks, published as 1.0.2 to npm.

are you interested in helping maintain this by the way? always looking for more collaborators, http://openopensource.org/ style

**Comment by jackboberg** [comment]
@maxogden I'd be happy to help.

**Comment by max-mapper** [comment]
WOOT. I added you on github and npm and to the COLLABORATORS.md file (using `npm i collaborator -g`)

**Pull request merged**
